{{- range $clusterSet, $value := .Values.clusterSets }}
---
apiVersion: apps.open-cluster-management.io/v1beta1
kind: GitOpsCluster
metadata:
  name: argo-acm-importer-{{ $clusterSet }}
  namespace: {{ $.Values.acm.gitops_namespace | default "openshift-gitops"}}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "7"
spec:
  argoServer:
    cluster: notused
    argoNamespace: {{ $.Values.acm.gitops_namespace | default "openshift-gitops"}}
  placementRef:
    kind: Placement
    apiVersion: cluster.open-cluster-management.io/v1beta1
    name: {{ $clusterSet }}
    namespace: {{ $.Values.acm.gitops_namespace | default "openshift-gitops"}}
{{- end }}
{{- range $clusterSet, $value := .Values.hubClusterSets }}
---
apiVersion: apps.open-cluster-management.io/v1beta1
kind: GitOpsCluster
metadata:
  name: argo-acm-importer-{{ $clusterSet }}
  namespace: {{ $.Values.acm.gitops_namespace | default "openshift-gitops"}}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "7"
spec:
  argoServer:
    cluster: notused
    argoNamespace: {{ $.Values.acm.gitops_namespace | default "openshift-gitops"}}
  placementRef:
    kind: Placement
    apiVersion: cluster.open-cluster-management.io/v1beta1
    name: {{ $clusterSet }}
    namespace: {{ $.Values.acm.gitops_namespace | default "openshift-gitops"}}
{{- end }}