apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: {{ .Values.acm.gitops_auto_clusterset }}
  namespace: {{ .Values.acm.gitops_namespace_dev | default "openshift-gitops-dev"}}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "6"
spec:
  clusterSets:
    - {{ .Values.acm.gitops_auto_clusterset }}
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists