apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-quay-deploy
  namespace: {{ .Values.policy_namespace }}
  annotations:
    policy.open-cluster-management.io/standards: NIST SP 800-53
    policy.open-cluster-management.io/categories: CA Security Assessment and Authorization
    policy.open-cluster-management.io/controls: CA-2 Security Assessments, CA-7 Continuous Monitoring
spec:
  disabled: false
  dependencies:
  - apiVersion: policy.open-cluster-management.io/v1
    compliance: Compliant
    kind: Policy
    name: policy-quay-operator-install
    namespace: {{ .Values.policy_namespace }}
  - apiVersion: policy.open-cluster-management.io/v1
    compliance: Compliant
    kind: Policy
    name: policy-storage-cluster
    namespace: {{ .Values.policy_namespace }}
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: {{ .Values.quay.enterpriseNamespace }}-ns
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: {{ .Values.quay.enterpriseNamespace }}
    {{- if .Values.quay.registry_config_bundle }}
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: quay-registry-config-bundle
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Secret
                metadata:
                  name: quay-registry-config-bundle
                  namespace: {{ .Values.quay.enterpriseNamespace }}
                type: Opaque 
                data: 
                  config.yaml: {{ .Values.quay.registry_config_bundle | toYaml | trim | b64enc }}
    {{- end }}
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: quay-registry
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: quay.redhat.com/v1
                kind: QuayRegistry
                metadata:
                  name: registry
                  namespace: {{ .Values.quay.enterpriseNamespace }}
                spec:
                  {{- if .Values.quay.registry_components }}
                  components:
                    {{- .Values.quay.registry_components | toYaml | trim | nindent 20 }}
                  {{- end }}
                  {{- if .Values.quay.registry_config_bundle }}
                  configBundleSecret: quay-registry-config-bundle
                  {{- end }}
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: placement-policy-quay-deploy
  namespace: {{ .Values.policy_namespace }}
spec:
  clusterSets:
  clusterSets:
  {{- range $clusterSet, $value := .Values.managedClusterSets }}
    - {{ $clusterSet }}
  {{- end }}
  {{- range $clusterSet, $value := .Values.hubClusterSets }}
    - {{ $clusterSet }}
  {{- end }}
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: 'autoshift.io/quay'
              operator: In
              values:
              - 'true'
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: placement-policy-quay-deploy
  namespace: {{ .Values.policy_namespace }}
placementRef:
  name: placement-policy-quay-deploy
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: policy-quay-deploy
    apiGroup: policy.open-cluster-management.io
    kind: Policy
