# Default values for rhtas-operator.
policy_namespace: open-cluster-policies
rhtasOperator:
  name: rhtas-operator
  namespace: openshift-operators
  channel: stable
  installPlanApproval: Automatic
  source: redhat-operators
  sourceNamespace: openshift-marketplace
# hubClusterSets:
#   hub:
#     labels:
#       test1: 'test'
# managedClusterSets:
#   managed:
#     labels:
#       test4: 'test'

### Labels Trusted Artifact Signer
# tas<bool>: If not set Developer Hub will not be managed
# tas-channel<String>: default stable
# tas-install-plan-approval<String>: default Automatic
# tas-source<String>: default redhat-operators
# tas-source-namespace<String>: default openshift-marketplace