apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argo-apps-day-2
  namespace: openshift-gitops
  labels:
    velero.io/exclude-from-backup: "true"
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/bcarr-rh/acm-policys.git
      revision: main
      directories:
      - path: 'apps/day-2/*'
  template:
    metadata:
      name: '{{ .path.basename }}'
      labels:
        app: argo-apps-day-2
        velero.io/exclude-from-backup: "true"
    spec:
      project: default
      source:
        path: '{{ .path.path }}'
        repoURL: https://github.com/bcarr-rh/acm-policys.git
        targetRevision: main
        helm:
          valueFiles:
          - values.yaml
      ignoreDifferences:
      - group: "apps"
        kind: "Project"
        jsonPointers:
        - /metadata/annotations
        - /metadata/labels
      syncPolicy:
        preserveResourcesOnDeletion: true
        automated:
          prune: false
          selfHeal: true
        syncOptions:
        - RespectIgnoreDifferences=true
      destination:
        server: https://kubernetes.default.svc
        namespace: openshift-gitops
