apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argo-apps-day-1
  namespace: openshift-gitops
  labels:
    velero.io/exclude-from-backup: "true"
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/bcarr-rh/acm-policys.git
      revision: main
      directories:
      - path: 'apps/day-1/*'
  template:
    metadata:
      name: '{{ .path.basename }}'
      labels:
        app: argo-apps-day-1
        velero.io/exclude-from-backup: "true"
    spec:
      project: default
      source:
        path: '{{ .path.path }}'
        repoURL: https://github.com/bcarr-rh/acm-policys.git
        targetRevision: main
        helm:
          valueFiles:
          - values.yaml
          valuesObject:
            hubClusterSets:
              hub:
                labels:
                  acs: 'true'
                  compliance: 'true'
                  loki: 'true'
                  logging: 'true'
                  coo: 'true'
              test-hub:
                labels:
                  test2: 'test'
            managedClusterSets:
              sandbox:
                labels:
                  test3: 'test'
              managed:
                labels:
                  acs: 'true'
                  compliance: 'true'
                  loki: 'true'
                  logging: 'true'
                  coo: 'true'
            clusters:
              nonprod:
                labels:
                  infra-nodes-numcpu: '8'
                  infra-nodes-memory-mib:  '24576'
                  infra-nodes-numcores-per-socket:  '4'
                  infra-nodes:  '6'
                  worker-nodes-numcpu:  '8'
                  worker-nodes-memory-mib:  '32768'
                  worker-nodes-numcores-per-socket:  '4'
                  worker-nodes:  '3'
              local-cluster: 
                labels: 
                  test-worked: 'true'
                  second-label: ''
      ignoreDifferences:
      - group: "apps"
        kind: "Project"
        jsonPointers:
        - /metadata/annotations
        - /metadata/labels
      syncPolicy:
        preserveResourcesOnDeletion: false
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - RespectIgnoreDifferences=true
        - Validate=false 
      destination:
        server: https://kubernetes.default.svc
        namespace: openshift-gitops
