# Default values for the gitops operator
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
autoshiftPolicyNamespace: open-cluster-policies
gitops:
  namespace: openshift-gitops-operator
  argoNamespace: openshift-gitops
  group: openshift-gitops-operator
  source: redhat-operators
  channel: latest
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic
  name: openshift-gitops-operator
  argoName: infra-gitops
  rbac_policies:
  - 'g, openshift-systems, role:admin'
  # OPTIONAL
  controller:
    limits:
      cpu: 2000m
      memory: 6Gi
    requests:
      cpu: 250m
      memory: 6Gi
  ha:
    enabled: false
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 250m
      memory: 128Mi
  redis:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 250m
      memory: 128Mi
  repo:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 250m
      memory: 256Mi    
  server:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 125m
      memory: 128Mi
  dex:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 250m
      memory: 128Mi

# hubClusterSets:
#   hub:
#     labels:
#       test1: 'test'
# managedClusterSets:
#   sandbox:
#     labels:
#       test3: 'test'
#   managed:
#     labels:
#       test4: 'test'
