# Default values for worker-nodes.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
autoshiftPolicyNamespace: open-cluster-policies
workerNodes:
  clusterSets:
    - managed
  zones:
    - us-east-2c