# Default values for pipelines.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
pipelines:
    name: openshift-pipelines-operator-rh
    namespace: openshift-operators
    channel: latest
    installPlanApproval: Automatic
    source: redhat-operators
    sourceNamespace: openshift-marketplace
# hubClusterSets:
#   hub:
#     labels:
#       test1: 'test'
# managedClusterSets:
#   managed:
#     labels:
#       test4: 'test'

### Labels OpenShift Pipelines
# pipelines<bool>: If not set Developer Hub will not be managed
# pipelines-channel<String>: default latest
# pipelines-install-plan-approval<String>: default Automatic
# pipelines-source<String>: default redhat-operators
# pipelines-source-namespace<String>: default openshift-marketplace