# This policy assumes that the Compliance Operator is installed and running on
# the managed clusters. It deploys a scan that checks the master and worker
# nodes, and verifies compliance with the OpenShift CIS security benchmark.
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-stig-scan
  namespace: {{ .Values.policy_namespace }}
  annotations:
    policy.open-cluster-management.io/standards: NIST SP 800-53
    policy.open-cluster-management.io/categories: CM Configuration Management
    policy.open-cluster-management.io/controls: CM-6 Configuration Settings
spec:
  disabled: false
  dependencies:
  - apiVersion: policy.open-cluster-management.io/v1
    compliance: Compliant
    kind: Policy
    name: policy-comp-operator
    namespace: {{ .Values.policy_namespace }}
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: compliance-stig-scan
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: musthave # this template creates role for compliance-operator error
              objectDefinition:
                kind: Role
                apiVersion: rbac.authorization.k8s.io/v1
                metadata:
                  name: compliance-operator-agg-patch-role
                  namespace: {{ .Values.compliance.namespace }}
                rules:
                  - verbs:
                      - create
                      - get
                      - update
                      - patch
                      - delete
                    apiGroups:
                      - compliance.openshift.io
                    resources:
                      - complianceremediations
                      - complianceremediations/status
            - complianceType: musthave # this template creates role binding for compliance-operator error
              objectDefinition:
                kind: RoleBinding
                apiVersion: rbac.authorization.k8s.io/v1
                metadata:
                  name: compliance-operator-agg-patch-rolebinding
                  namespace: {{ .Values.compliance.namespace }}
                subjects:
                  - kind: ServiceAccount
                    name: remediation-aggregator
                    namespace: {{ .Values.compliance.namespace }}
                roleRef:
                  apiGroup: rbac.authorization.k8s.io
                  kind: Role
                  name: compliance-operator-agg-patch-role

            - complianceType: musthave # this template creates ScanSettingBinding:stig
              objectDefinition:
                apiVersion: compliance.openshift.io/v1alpha1
                kind: ScanSettingBinding
                metadata:
                  name: stig
                  namespace: {{ .Values.compliance.namespace }}
                profiles:
                  - apiGroup: compliance.openshift.io/v1alpha1
                    kind: Profile
                    name: ocp4-stig
                  - apiGroup: compliance.openshift.io/v1alpha1
                    kind: Profile
                    name: ocp4-stig-node
                  - apiGroup: compliance.openshift.io/v1alpha1
                    kind: Profile
                    name: rhcos4-stig
                settingsRef:
                  apiGroup: compliance.openshift.io/v1alpha1
                  kind: ScanSetting
                  name: default
          
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: compliance-suite-stig
        spec:
          remediationAction: inform
          severity: high
          object-templates:
            - complianceType: musthave # this template checks if scan has completed by checking the status field
              objectDefinition:
                apiVersion: compliance.openshift.io/v1alpha1
                kind: ComplianceSuite
                metadata:
                  name: stig
                  namespace: {{ .Values.compliance.namespace }}
                status:
                  phase: DONE
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: placement-policy-stig-scan
  namespace: {{ .Values.policy_namespace }}
spec:
  clusterSets:
  {{- range $clusterSet, $value := $.Values.managedClusterSets }}
    - {{ $clusterSet }}
  {{- end }}
  {{- range $clusterSet, $value := $.Values.hubClusterSets }}
    - {{ $clusterSet }}
  {{- end }}
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: 'autoshift.io/compliance'
              operator: In
              values:
              - 'true'
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: placement-policy-stig-scan
  namespace: {{ .Values.policy_namespace }}
placementRef:
  name: placement-policy-stig-scan
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: policy-stig-scan
    apiGroup: policy.open-cluster-management.io
    kind: Policy