{{- range $clusterSet, $value := .Values.clusterSets }}
{{- range $team, $teamjson := .Values.teams }}
---
apiVersion: apps.open-cluster-management.io/v1beta1
kind: GitOpsCluster
metadata:
  name: argo-acm-importer
  namespace: openshift-gitops-{{ $team }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "7"
spec:
  argoServer:
    cluster: notused
    argoNamespace: openshift-gitops-{{ $team }}
  placementRef:
    kind: Placement
    apiVersion: cluster.open-cluster-management.io/v1beta1
    name: {{ $clusterSet }}
    namespace: openshift-gitops-{{ $team }}
{{- end }}
{{- end }}