{{- if .Values.hubClusterSets }}
{{- range $team, $value := .Values.teams }}
---
apiVersion: argoproj.io/v1alpha1
kind: RolloutManager
metadata:
  name: argo-rollout
  namespace: openshift-gitops-{{ $team }}
  labels:
    example: basic
spec: {}
{{- end }}
{{- end }}