apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ .Release.Name }}-argo-apps-day-2
  namespace: openshift-gitops
  labels:
    velero.io/exclude-from-backup: "true"
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: {{ .Values.autoshiftGitRepo }}
      revision: {{ .Values.autoshiftGitBranchTag }}
      directories:
      - path: 'apps/day-2/*'
  template:
    metadata:
      name: '{{ .Release.Name }}-{{"{{"}} .path.basename {{"}}"}}'
      labels:
        app: argo-apps-day-2
        velero.io/exclude-from-backup: "true"
    spec:
      project: default
      source:
        path: '{{"{{"}} .path.path {{"}}"}}'
        repoURL: {{ .Values.autoshiftGitRepo }}
        targetRevision: {{ .Values.autoshiftGitBranchTag }}
        helm:
          valueFiles:
          - values.yaml
          valuesObject:
            policy_namespace: {{ printf "policies-%s" .Release.Name }}
            {{- if .Values.hubClusterSets }}
            hubClusterSets:
            {{-  range $cluster, $clustervalue := .Values.hubClusterSets }}
              {{ $cluster }}:
                labels:
                {{-  range $labelkey, $labelvalue := $clustervalue.labels }}
                  {{ $labelkey }}: '{{ $labelvalue }}'
                {{- end }}
            {{- end }}
            {{- end }}
            {{- if .Values.managedClusterSets }}
            managedClusterSets:
              {{-  range $cluster, $clustervalue := .Values.managedClusterSets }}
              {{ $cluster }}:
                labels:
                {{-  range $labelkey, $labelvalue := $clustervalue.labels }}
                  {{ $labelkey }}: '{{ $labelvalue }}'
                {{- end }}
            {{- end }}
            {{- end }}
            {{- if .Values.clusters }}
            clusters:
              {{-  range $cluster, $clustervalue := .Values.clusters }}
              {{ $cluster }}:
                labels:
                {{-  range $labelkey, $labelvalue := $clustervalue.labels }}
                  {{ $labelkey }}: '{{ $labelvalue }}'
                {{- end }}
            {{- end }}
            {{- end }}
      ignoreDifferences:
      - group: "apps"
        kind: "Project"
        jsonPointers:
        - /metadata/annotations
        - /metadata/labels
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - RespectIgnoreDifferences=true
        - CreateNamespace=true
      destination:
        server: https://kubernetes.default.svc
        namespace: {{ printf "policies-%s" .Release.Name }}