# Default values for loki.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
devspaces:
    name: devspaces
    namespace: openshift-operators-redhat
    channel: stable
    installPlanApproval: Automatic
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    clusterSets:
      - hub
      - managed