# Default values for loki.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
loki:
    name: loki-operator
    namespace: openshift-operators-redhat
    channel: stable-6.2
    installPlanApproval: Automatic
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    size: 1x.extra-small
    storageClass: gp3-csi
    lokistackName: logging-lokistack
logging:
    name: cluster-logging
    namespace: openshift-logging
    channel: stable-6.2
    installPlanApproval: Automatic
    source: redhat-operators
    sourceNamespace: openshift-marketplace
coo:
    name: cluster-observability-operator
    namespace: openshift-cluster-observability-operator
    channel: stable
    installPlanApproval: Automatic
    source: redhat-operators
    sourceNamespace: openshift-marketplace
# hubClusterSets:
#   hub:
#     labels:
#       test1: 'test'
# managedClusterSets:
#   managed:
#     labels:
#       test4: 'test'

# Labels 
# loki<bool>: If not set Loki will not be managed. Dependent on ODF Multi Object Gateway
# loki-channel<String>: default stable-6.1
# loki-install-plan-approval<String>: default Automatic
# loki-source<String>: default redhat-operators
# loki-sourcenamespace<String>: default openshift-marketplace
# loki-size<String>: default 1x.extra-small
# loki-storageclass<String>: default gp3-csi
# loki-lokistack-name<String>: default logging-lokistack

# logging<bool>: If not set OpenShift Logging will not be managed, Dependent on Loki and COO
# logging-channel<String>: default stable-6.1
# logging-install-plan-approval<String>: default Automatic
# logging-source<String>: default redhat-operators
# logging-source-namespace<String>: default openshift-marketplace

# coo<bool>: If not set Cluster Observability Operator will not be managed
# coo-channel<String>: default stable
# coo-install-plan-approval<String>: default Automatic
# coo-source<String>: default redhat-operators
# coo-source-namespace<String>: default openshift-marketplace