apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-admin-{{ .Values.gitops.argoName }}-argocd-application-controller
  annotations:
    helm.sh/hook-weight: "3"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: {{ .Values.gitops.argoName }}-argocd-application-controller
  namespace: {{ .Values.gitops.argoNamespace }}
