apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: {{ .Values.gitops.namespace | default "openshift-gitops-operator" }}
  namespace: {{ .Values.gitops.namespace | default "openshift-gitops-operator"}}
  annotations:
    helm.sh/hook-weight: "1"
spec:
  upgradeStrategy: Default