---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.gitops.namespace | default "openshift-gitops-operator"}}
  annotations:
    helm.sh/hook-weight: "0"
  labels:
    openshift.io/cluster-monitoring: "true"
spec: {}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.gitops.argoNamespace | default "openshift-gitops"}}
  annotations:
    helm.sh/hook-weight: "0"
  labels:
    openshift.io/cluster-monitoring: "true"
spec: {}