{{- if .Values.secrets }}
{{- range $secret := .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secret.name }}
  namespace: {{ $.Values.gitops.argoNamespace }}
  labels:
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
type: kubernetes.io/basic-auth
stringData:
  password: {{ $secret.password | quote }}
  username:  {{ $secret.username | quote }}
  sshPrivateKey: {{ $secret.sshPrivateKey | quote }}
{{- end }}
{{- end }}