# Default values for the autoshift
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

autoshiftGitRepo: https://github.com/auto-shift/autoshiftv2.git
autoshiftGitBranchTag: main

# Hub Cluster Sets with Feature Flags. Blank will remove
hubClusterSets:
  hub:
    labels:
      ### infra-nodes
      infra-nodes: ''
      infra-nodes-numcpu: ''
      infra-nodes-memory-mib: ''
      infra-nodes-numcores-per-socket: ''
      infra-nodes-zones: ''
      ### worker-nodes
      worker-nodes: ''
      worker-nodes-numcpu: ''
      worker-nodes-memory-mib: ''
      worker-nodes-numcores-per-socket: ''
      worker-nodes-zones: ''
      ### storage-nodes
      storage-nodes: ''
      storage-nodes-numcpu: ''
      storage-nodes-memory-mib: ''
      storage-nodes-numcores-per-socket: ''
      storage-nodes-zones: ''
      ### Advanced Cluster Security
      acs: 'true'
      acs-channel: stable
      acs-install-plan-approval: Automatic
      acs-source: redhat-operators
      acs-source-namespace: openshift-marketplace
      ### Developer Spaces
      dev-spaces: 'true'
      dev-spaces-channel: stable
      dev-spaces-install-plan-approval:  Automatic
      dev-spaces-source: redhat-operators
      dev-spaces-source-namespace: openshift-marketplace
      ### Developer OpenShift Gitops
      gitops-dev: 'true'
      gitops-dev-teams: 'A,B'
      ### Loki
      loki: 'true' 
      loki-channel: stable-6.2
      loki-install-plan-approval: Automatic
      loki-source: redhat-operators
      loki-source-namespace: openshift-marketplace
      loki-size: 1x.extra-small
      loki-storageclass: gp3-csi
      loki-lokistack-name: logging-lokistack
      ### OpenShift Logging
      logging: 'true'
      logging-channel:  stable-6.2
      logging-install-plan-approval: Automatic
      logging-source: redhat-operators
      logging-source-namespace: openshift-marketplace
      ### Cluster Observability Operator
      coo: 'true'
      coo-channel: stable
      coo-install-plan-approval: Automatic
      coo-source: redhat-operators
      coo-source-namespace: openshift-marketplace
      ### Compliance Operator Stig Apply
      compliance: 'true'
      compliance-name: compliance-operator
      compliance-install-plan-approval: Automatic
      compliance-source: redhat-operators
      compliance-source-namespace: openshift-marketplace
      compliance-channel: stable
# Spoke Cluster Sets with Feature Flags. Blank will remove
managedClusterSets:
  managed:
    labels:
      ### infra-nodes
      infra-nodes: ''
      infra-nodes-numcpu: ''
      infra-nodes-memory-mib: ''
      infra-nodes-numcores-per-socket: ''
      infra-nodes-zones: ''
      ### worker-nodes
      worker-nodes: ''
      worker-nodes-numcpu: ''
      worker-nodes-memory-mib: ''
      worker-nodes-numcores-per-socket: ''
      worker-nodes-zones: ''
      ### storage-nodes
      storage-nodes: ''
      storage-nodes-numcpu: ''
      storage-nodes-memory-mib: ''
      storage-nodes-numcores-per-socket: ''
      storage-nodes-zones: ''
      ### Advanced Cluster Security
      acs: 'true'
      acs-channel: stable
      acs-install-plan-approval: Automatic
      acs-source: redhat-operators
      acs-source-namespace: openshift-marketplace
      ### Developer Spaces
      dev-spaces: 'true'
      dev-spaces-channel: stable
      dev-spaces-install-plan-approval:  Automatic
      dev-spaces-source: redhat-operators
      dev-spaces-source-namespace: openshift-marketplace
      ### Developer OpenShift Gitops
      gitops-dev: 'true'
      gitops-dev-teams: 'A,B'
      ### Loki
      loki: 'true' 
      loki-channel: stable-6.2
      loki-install-plan-approval: Automatic
      loki-source: redhat-operators
      loki-source-namespace: openshift-marketplace
      loki-size: 1x.extra-small
      loki-storageclass: gp3-csi
      loki-lokistack-name: logging-lokistack
      ### OpenShift Logging
      logging: 'true'
      logging-channel:  stable-6.2
      logging-install-plan-approval: Automatic
      logging-source: redhat-operators
      logging-source-namespace: openshift-marketplace
      ### Cluster Observability Operator
      coo: 'true'
      coo-channel: stable
      coo-install-plan-approval: Automatic
      coo-source: redhat-operators
      coo-source-namespace: openshift-marketplace
      ### Compliance Operator Stig Apply
      compliance: 'true'
      compliance-name: compliance-operator
      compliance-install-plan-approval: Automatic
      compliance-source: redhat-operators
      compliance-source-namespace: openshift-marketplace
      compliance-channel: stable
# Cluster override Feature Flags. Blank will remove
# clusters:
#   nonprod:
#     labels:
#       infra-nodes-numcpu: '8'
#       infra-nodes-memory-mib:  '24576'
#       infra-nodes-numcores-per-socket:  '4'
#       infra-nodes:  '6'
#       worker-nodes-numcpu:  '8'
#       worker-nodes-memory-mib:  '32768'
#       worker-nodes-numcores-per-socket:  '4'
#       worker-nodes:  '3'