# Default values for the autoshift
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

autoshiftGitRepo: https://github.com/bcarr-rh/acm-policys.git
autoshiftGitBranchTag: managed-hub-testing
autoshiftPolicyNamespace: "open-cluster-policies"

selfManagedHubSet: hub

# Optional: If you want to exclude policies from all clusters, you can add the folder name here.
# excludePolicies:
#   - infra-nodes
#   - worker-nodes


# Hub Cluster Sets with Feature Flags. Blank will remove
hubClusterSets:
  hubofhubs:
    labels:
      self-managed: 'true'
      ### Advance Cluster Manager
      acm-channel: release-2.13
      acm-install-plan-approval: Automatic
      acm-source: redhat-operators
      acm-source-namespace: openshift-marketplace
      acm-availability-config: 'basic'
      ### infra-nodes
      infra-nodes: '4'
      infra-nodes-numcpu: ''
      infra-nodes-memory-mib: ''
      infra-nodes-numcores-per-socket: ''
      infra-nodes-zones: 'us-east-2c'
      ### worker-nodes
      worker-nodes: ''
      worker-nodes-numcpu: ''
      worker-nodes-memory-mib: ''
      worker-nodes-numcores-per-socket: ''
      worker-nodes-zones: ''
      ### storage-nodes
      storage-nodes: ''
      storage-nodes-numcpu: ''
      storage-nodes-memory-mib: ''
      storage-nodes-numcores-per-socket: ''
      storage-nodes-zones: ''
      ### OpenShift Data Foundation
      odf: 'false'
      odf-multi-cloud-gateway: standalone
      odf-nooba-pvpool: ''
      odf-nooba-store-size: ''
      odf-nooba-store-num-volumes: ''
      odf-ocs-storage-class-name: gp3-csi
      odf-ocs-storage-size: ''
      odf-ocs-storage-count: ''
      odf-ocs-storage-replicas: ''
      odf-resource-profile: balanced
      odf-channel: stable-4.17
      odf-install-plan-approval: Automatic
      odf-source: redhat-operators
      odf-source-namespace: openshift-marketplace
      ### Advanced Cluster Security
      acs: 'true'
      acs-channel: stable
      acs-install-plan-approval: Automatic
      acs-source: redhat-operators
      acs-source-namespace: openshift-marketplace
      ### Developer Spaces
      dev-spaces: 'false'
      dev-spaces-channel: stable
      dev-spaces-install-plan-approval:  Automatic
      dev-spaces-source: redhat-operators
      dev-spaces-source-namespace: openshift-marketplace
      ### Developer Hub
      dev-hub: 'false'
      dev-hub-channel: fast
      dev-hub-install-plan-approval: Automatic
      dev-hub-source: redhat-operators
      dev-hub-source-namespace: openshift-marketplace
      ### OpenShift Pipelines
      pipelines: 'false'
      pipelines-channel: latest
      pipelines-install-plan-approval: Automatic
      pipelines-source: redhat-operators
      pipelines-source-namespace: openshift-marketplace
      ### Trusted Artifact Signer
      tas: 'false'
      tas-channel:  stable
      tas-install-plan-approval: Automatic
      tas-source: redhat-operators
      tas-source-namespace: openshift-marketplace
      ### Quay
      quay: 'false'
      quay-channel: stable-3.13
      quay-install-plan-approval: Automatic
      quay-source: redhat-operators
      quay-source-namespace: openshift-marketplace
      ### Developer OpenShift Gitops
      gitops-dev: 'false'
      ### Loki
      loki: 'false' 
      loki-channel: stable-6.2
      loki-install-plan-approval: Automatic
      loki-source: redhat-operators
      loki-source-namespace: openshift-marketplace
      loki-size: 1x.extra-small
      loki-storageclass: gp3-csi
      loki-lokistack-name: logging-lokistack
      ### OpenShift Logging
      logging: 'false'
      logging-channel:  stable-6.2
      logging-install-plan-approval: Automatic
      logging-source: redhat-operators
      logging-source-namespace: openshift-marketplace
      ### Cluster Observability Operator
      coo: 'false'
      coo-channel: stable
      coo-install-plan-approval: Automatic
      coo-source: redhat-operators
      coo-source-namespace: openshift-marketplace
      ### Compliance Operator Stig Apply
      compliance: 'false'
      compliance-name: compliance-operator
      compliance-install-plan-approval: Automatic
      compliance-source: redhat-operators
      compliance-source-namespace: openshift-marketplace
      compliance-channel: stable
  managed-hub:
    labels:
      ### infra-nodes
      infra-nodes: '4'
      infra-nodes-numcpu: ''
      infra-nodes-memory-mib: ''
      infra-nodes-numcores-per-socket: ''
      infra-nodes-zones: 'us-east-2c'
      ### worker-nodes
      worker-nodes: ''
      worker-nodes-numcpu: ''
      worker-nodes-memory-mib: ''
      worker-nodes-numcores-per-socket: ''
      worker-nodes-zones: ''
      ### storage-nodes
      storage-nodes: ''
      storage-nodes-numcpu: ''
      storage-nodes-memory-mib: ''
      storage-nodes-numcores-per-socket: ''
      storage-nodes-zones: ''
      ### OpenShift Data Foundation
      odf: 'false'
      odf-multi-cloud-gateway: standalone
      odf-nooba-pvpool: ''
      odf-nooba-store-size: ''
      odf-nooba-store-num-volumes: ''
      odf-ocs-storage-class-name: gp3-csi
      odf-ocs-storage-size: ''
      odf-ocs-storage-count: ''
      odf-ocs-storage-replicas: ''
      odf-resource-profile: balanced
      odf-channel: stable-4.17
      odf-install-plan-approval: Automatic
      odf-source: redhat-operators
      odf-source-namespace: openshift-marketplace
      ### Advanced Cluster Security
      acs: 'false'
      acs-channel: stable
      acs-install-plan-approval: Automatic
      acs-source: redhat-operators
      acs-source-namespace: openshift-marketplace
      ### Developer Spaces
      dev-spaces: 'false'
      dev-spaces-channel: stable
      dev-spaces-install-plan-approval:  Automatic
      dev-spaces-source: redhat-operators
      dev-spaces-source-namespace: openshift-marketplace
      ### Developer Hub
      dev-hub: 'false'
      dev-hub-channel: fast
      dev-hub-install-plan-approval: Automatic
      dev-hub-source: redhat-operators
      dev-hub-source-namespace: openshift-marketplace
      ### OpenShift Pipelines
      pipelines: 'false'
      pipelines-channel: latest
      pipelines-install-plan-approval: Automatic
      pipelines-source: redhat-operators
      pipelines-source-namespace: openshift-marketplace
      ### Trusted Artifact Signer
      tas: 'false'
      tas-channel:  stable
      tas-install-plan-approval: Automatic
      tas-source: redhat-operators
      tas-source-namespace: openshift-marketplace
      ### Quay
      quay: 'false'
      quay-channel: stable-3.13
      quay-install-plan-approval: Automatic
      quay-source: redhat-operators
      quay-source-namespace: openshift-marketplace
      ### Developer OpenShift Gitops
      gitops-dev: 'false'
      ### Loki
      loki: 'false' 
      loki-channel: stable-6.2
      loki-install-plan-approval: Automatic
      loki-source: redhat-operators
      loki-source-namespace: openshift-marketplace
      loki-size: 1x.extra-small
      loki-storageclass: gp3-csi
      loki-lokistack-name: logging-lokistack
      ### OpenShift Logging
      logging: 'false'
      logging-channel:  stable-6.2
      logging-install-plan-approval: Automatic
      logging-source: redhat-operators
      logging-source-namespace: openshift-marketplace
      ### Cluster Observability Operator
      coo: 'false'
      coo-channel: stable
      coo-install-plan-approval: Automatic
      coo-source: redhat-operators
      coo-source-namespace: openshift-marketplace
      ### Compliance Operator Stig Apply
      compliance: 'false'
      compliance-name: compliance-operator
      compliance-install-plan-approval: Automatic
      compliance-source: redhat-operators
      compliance-source-namespace: openshift-marketplace
      compliance-channel: stable
# Spoke Cluster Sets with Feature Flags. Blank will remove
managedClusterSets:
  managed:
    labels:
      ### infra-nodes
      infra-nodes: '4'
      infra-nodes-numcpu: ''
      infra-nodes-memory-mib: ''
      infra-nodes-numcores-per-socket: ''
      infra-nodes-zones: ''
      ### worker-nodes
      worker-nodes: ''
      worker-nodes-numcpu: ''
      worker-nodes-memory-mib: ''
      worker-nodes-numcores-per-socket: ''
      worker-nodes-zones: ''
      ### storage-nodes
      storage-nodes: ''
      storage-nodes-numcpu: ''
      storage-nodes-memory-mib: ''
      storage-nodes-numcores-per-socket: ''
      storage-nodes-zones: ''
      ### OpenShift Data Foundation
      odf: 'false'
      odf-multi-cloud-gateway: standalone
      odf-nooba-pvpool: ''
      odf-nooba-store-size: ''
      odf-nooba-store-num-volumes: ''
      odf-ocs-storage-class-name: gp3-csi
      odf-ocs-storage-size: ''
      odf-ocs-storage-count: ''
      odf-ocs-storage-replicas: ''
      odf-resource-profile: balanced
      odf-channel: stable-4.17
      odf-install-plan-approval: Automatic
      odf-source: redhat-operators
      odf-source-namespace: openshift-marketplace
      ### Advanced Cluster Security
      acs: 'true'
      acs-channel: stable
      acs-install-plan-approval: Automatic
      acs-source: redhat-operators
      acs-source-namespace: openshift-marketplace
      ### Developer Spaces
      dev-spaces: 'false'
      dev-spaces-channel: '' #stable
      dev-spaces-install-plan-approval:  '' #Automatic
      dev-spaces-source: redhat-operators
      dev-spaces-source-namespace: openshift-marketplace
      ### Developer Hub
      dev-hub: 'false'
      dev-hub-channel: '' #fast
      dev-hub-install-plan-approval: '' #Automatic
      dev-hub-source: '' #redhat-operators
      dev-hub-source-namespace: '' #openshift-marketplace
      ### OpenShift Pipelines
      pipelines: 'false'
      pipelines-channel: '' #latest
      pipelines-install-plan-approval: '' #Automatic
      pipelines-source: '' #redhat-operators
      pipelines-source-namespace: '' #openshift-marketplace
      ### Trusted Artifact Signer
      tas: 'false'
      tas-channel:  '' #latest
      tas-install-plan-approval: '' #Automatic
      tas-source: '' #redhat-operators
      tas-source-namespace: '' #openshift-marketplace
      ### Quay
      quay: 'false'
      quay-channel: '' # stable-3.13
      quay-install-plan-approval: '' # Automatic
      quay-source: '' # redhat-operators
      quay-source-namespace: '' # openshift-marketplace
      ### Developer OpenShift Gitops
      gitops-dev: 'false'
      gitops-dev-team-dev: 'true'
      ### Loki
      loki: 'true' 
      loki-channel: stable-6.2
      loki-install-plan-approval: Automatic
      loki-source: redhat-operators
      loki-source-namespace: openshift-marketplace
      loki-size: 1x.extra-small
      loki-storageclass: gp3-csi
      loki-lokistack-name: logging-lokistack
      ### OpenShift Logging
      logging: 'true'
      logging-channel:  stable-6.2
      logging-install-plan-approval: Automatic
      logging-source: redhat-operators
      logging-source-namespace: openshift-marketplace
      ### Cluster Observability Operator
      coo: 'true'
      coo-channel: stable
      coo-install-plan-approval: Automatic
      coo-source: redhat-operators
      coo-source-namespace: openshift-marketplace
      ### Compliance Operator Stig Apply
      compliance: 'false'
      compliance-name: compliance-operator
      compliance-install-plan-approval: Automatic
      compliance-source: redhat-operators
      compliance-source-namespace: openshift-marketplace
      compliance-channel: stable
# Cluster override Feature Flags. Blank will remove
# clusters:
#   nonprod:
#     labels:
#       infra-nodes-numcpu: '8'
#       infra-nodes-memory-mib:  '24576'
#       infra-nodes-numcores-per-socket:  '4'
#       infra-nodes:  '6'
#       worker-nodes-numcpu:  '8'
#       worker-nodes-memory-mib:  '32768'
#       worker-nodes-numcores-per-socket:  '4'
#       worker-nodes:  '3'
