apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: {{ .Values.acm.namespace }}
  namespace: {{ .Values.acm.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  targetNamespaces:
  - {{ .Values.acm.namespace }}