# Default values for quay.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
autoshiftPolicyNamespace: open-cluster-policies
quay:
    name: quay-operator
    namespace: quay-operator
    channel: stable-3.13
    installPlanApproval: Automatic
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    enterpriseNamespace: quay-enterprise
    registry_config_bundle:
      FEATURE_USER_INITIALIZE: true
      BROWSER_API_CALLS_XHR_ONLY: false
      SUPER_USERS:
      - quayadmin
      FEATURE_USER_CREATION: false
    registry_components:
      - kind: clair
        managed: true
      - kind: postgres
        managed: true
      - kind: objectstorage
        managed: true
      - kind: redis
        managed: true
      - kind: horizontalpodautoscaler
        managed: true
      - kind: route
        managed: true
      - kind: mirror
        managed: true
      - kind: monitoring
        managed: true
      - kind: tls
        managed: true
      - kind: quay
        managed: true
      - kind: clairpostgres
        managed: true

# hubClusterSets:
#   hub:
#     labels:
#       test1: 'test'
# managedClusterSets:
#   managed:
#     labels:
#       test4: 'test'

### Labels Quay
# quay<bool>: If not set Quay will not be managed
# quay-channel<String>: default stable-3.13
# quay-install-plan-approval<String>: default Automatic
# quay-source<String>: default redhat-operators
# quay-source-namespace<String>: default openshift-marketplace