{{- if (.Values.enabled | default false) }}
{{- $allClusterSets := (merge (.Values.hubClusterSets | default dict) (.Values.managedClusterSets | default dict)) }}
{{- range $clusterSetKey, $clusterSetValue := $allClusterSets }}
{{- $hubClusterSet := $.Values.hubClusterSet | default "hub" }}
{{- $policyName := printf "policy-%s-cluster-labels" $clusterSetKey }}
{{- $configPolicyName := printf "cluster-labels-%s" $clusterSetKey }}
{{- $placementName := printf "placement-%s" $policyName }}
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: {{ $policyName }}
  namespace: {{ $.Values.policy_namespace }}
  annotations:
    policy.open-cluster-management.io/categories: CM Configuration Management
    policy.open-cluster-management.io/controls: CM-2 Baseline Configuration
    policy.open-cluster-management.io/standards: NIST SP 800-53
spec:
  disabled: false
  remediationAction: enforce
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: {{ $configPolicyName }}
          annotations:
        spec:
          severity: high 
          object-templates-raw: |
            [
              {{ "{{-" }} $thisClusterSet := "{{ $clusterSetKey }}" {{ "}}" }}
              {{ "{{-" }} $clusters := (lookup "cluster.open-cluster-management.io/v1" "ManagedCluster" "" "").items {{ "}}" }}
              {{ "{{-" }} $lastIndex := sub (len $clusters) 1 {{ "}}" }}
              {{ "{{-" }} range $index, $value := $clusters {{ "}}" }}
                {{ "{{-" }} $clusterSet := ((index $value.metadata.labels "cluster.open-cluster-management.io/clusterset") | default "") {{ "}}" }}
                {{ "{{-" }} if or (eq $clusterSet "") (ne $clusterSet $thisClusterSet) {{ "}}" }}
                  {{ "{{-" }} continue {{ "}}" }}
                {{ "{{-" }} end {{ "}}" }}
                {{ "{{-" }} $newLabels := dict {{ "}}" }}
                {{ "{{-" }} $managedCluster := $value.metadata.name {{ "}}" }}
                {{ "{{-" }} $existingClusterLabels := $value.metadata.labels {{ "}}" }}
                {{ "{{-" }} range $existingKey, $existingValue := $existingClusterLabels {{ "}}" }}
                  {{ "{{-" }} if ($existingKey | hasPrefix "{{ $.Values.autoshiftLabelPrefix }}") {{ "}}" }}
                    {{ "{{-" }} $_ := unset $existingClusterLabels $existingKey {{ "}}" }}
                  {{ "{{-" }} end {{ "}}" }}
                {{ "{{-" }} end {{ "}}" }}
                {{ "{{/*" }} // Setting up this block to work on the label extraction code and maybe make it more readable :) {{ "*/}}" }}
                  {{ "{{-" }} $clusterSetConfigMap := (lookup "v1" "ConfigMap" "{{ $.Values.policy_namespace }}" (printf "cluster-set.%s" $clusterSet)) | default dict {{ "}}" }}   
                  {{ "{{-" }} $clusterSetConfigMapData := (index $clusterSetConfigMap "data") | default dict {{ "}}" }} 
                  {{ "{{-" }} $clusterSetConfigMapValues := (index $clusterSetConfigMapData "values") | default "" {{ "}}" }}  
                  {{ "{{-" }} $clusterSetLabels := (index ($clusterSetConfigMapValues | fromJson | default dict) "labels") | default dict {{ "}}" }} 
                  {{ "{{-" }} $clusterConfigMap := (lookup "v1" "ConfigMap" "{{ $.Values.policy_namespace }}" (printf "managed-cluster.%s" $value.metadata.name)) | default dict {{ "}}" }}   
                  {{ "{{-" }} $clusterConfigMapData := (index $clusterConfigMap "data") | default dict {{ "}}" }} 
                  {{ "{{-" }} $clusterConfigMapValues := (index $clusterConfigMapData "values") | default "" {{ "}}" }}  
                  {{ "{{-" }} $clusterLabels := (index ($clusterConfigMapValues | fromJson | default dict) "labels") | default dict {{ "}}" }} 
                {{ "{{/*" }} // End of label extraction {{ "*/}}" }}
                {{ "{{-" }} $configMapLabels := merge $clusterLabels $clusterSetLabels {{ "}}" }}
                {{ "{{-" }} $labels := merge $clusterLabels $clusterSetLabels $existingClusterLabels {{ "}}" }} 
                {{ "{{-" }} range $label, $labelValue := $labels {{ "}}" }}
                  {{ "{{-" }} if not (and ($label | hasPrefix "{{ $.Values.autoshiftLabelPrefix }}") (eq $labelValue "_")) {{ "}}" }}
                    {{ "{{-" }} $_ := set $newLabels $label $labelValue {{ "}}" }}
                  {{ "{{-" }} end {{ "}}" }}
                {{ "{{-" }} end {{ "}}" }}
                {{ "{{-" }} $metadata := set $value.metadata "labels" $newLabels {{ "}}" }}
                {{ "{{-" }} $objectDefinition := set $value "metadata" $metadata {{ "}}" }}
                {{ "{{-" }} $_ := unset $objectDefinition "status" {{ "}}" }}
                {
                  "complianceType": "mustonlyhave",
                  "objectDefinition": {{ "{{" }} $objectDefinition | toRawJson  {{ "}}" }}
                }{{ "{{-" }} if ne $lastIndex $index {{ "}}" }},{{ "{{-" }} end {{ "}}" }}
              {{ "{{-" }} end {{ "}}" }}
            ]
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: {{ $placementName }}
  namespace: {{ $.Values.policy_namespace }}
spec:
  clusterSets:
    - {{ $.Values.selfManagedHubSet }}
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: {{ $placementName }}
  namespace: {{ $.Values.policy_namespace }}
placementRef:
  name: {{ $placementName}}
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: {{ $policyName }}
    apiGroup: policy.open-cluster-management.io
    kind: Policy
---
{{- end }}
{{- end }}
{{/* $clusterSetLabels := (index ((index (index ((lookup "v1" "ConfigMap" "{{ $.Values.policy_namespace }}" (printf "cluster-set.%s"  $clusterSet)) | default dict) "data" | default dict) "values" | default "" | fromJson) | default dict) "labels") | default dict */}}
{{/* $clusterLabels := (index ((index (index ((lookup "v1" "ConfigMap" "{{ $.Values.policy_namespace }}" (printf "managed-cluster.%s"  $value.metadata.name)) | default dict) "data" | default dict) "values" | default "" | fromJson) | default dict) "labels") | default dict */}}