apiVersion: operator.open-cluster-management.io/v1
kind: MultiClusterHub
metadata:
  name: multiclusterhub
  namespace: {{ .Values.acm.namespace }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true,ServerSideApply=true,Delete=false,PrunePropagationPolicy=orphan
    argocd.argoproj.io/sync-wave: "3"
spec:
  availabilityConfig: {{ .Values.acm.availabilityConfig | default "Basic" }}
{{ if .Values.acm.disable_hub_self_management }}
  disableHubSelfManagement: {{ .Values.acm.disable_hub_self_management }}
{{ end}}