---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: autoshift-policy-service-account
  namespace: {{ .Values.policy_namespace }}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: autoshift-policy-service-account-cluster-reader
subjects:
  - kind: ServiceAccount
    name: autoshift-policy-service-account
    namespace: {{ .Values.policy_namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-reader