# This policy verifies the installation of the official & supported version of
# the Compliance Operator on the managed clusters.
#
# If set to "enforce" it'll install the operator.
#
# Note that OpenShift 4.18 is required.
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-noobaa-backing-store
  namespace: open-cluster-policies
  annotations:
    policy.open-cluster-management.io/standards: NIST SP 800-53
    policy.open-cluster-management.io/categories: CA Security Assessment and Authorization
    policy.open-cluster-management.io/controls: CA-2 Security Assessments, CA-7 Continuous Monitoring
spec:
  dependencies:
    - name: policy-storage-cluster
      namespace: open-cluster-policies
      apiVersion: policy.open-cluster-management.io/v1
      compliance: Compliant
      kind: Policy    
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: noobaa-backing-store
        spec:
          remediationAction: inform # will be overridden by remediationAction in parent policy
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: noobaa.io/v1alpha1
                kind: BackingStore
                metadata:
                  name: noobaa-default-backing-store
                  namespace: {{ .Values.odf.namespace }}
                spec:
                  pvPool:
                    numVolumes: 1
                    resources:
                      limits:
                        cpu: 1000m
                        memory: 4000Mi
                      requests:
                        cpu: 500m
                        memory: 500Mi
                        storage: 500Gi
                    secret: {}
                  type: pv-pool
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: placement-policy-noobaa-backing-store
  namespace: open-cluster-policies
spec:
  clusterSets:
  {{- range $clusterSet, $value := $.Values.managedClusterSets }}
    - {{ $clusterSet }}
  {{- end }}
  {{- range $clusterSet, $value := $.Values.hubClusterSets }}
    - {{ $clusterSet }}
  {{- end }}
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: placement-policy-noobaa-backing-store
  namespace: open-cluster-policies
placementRef:
  name: placement-policy-noobaa-backing-store
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: policy-noobaa-backing-store
    apiGroup: policy.open-cluster-management.io
    kind: Policy
