# This policy verifies the installation of the official & supported version of
# the Compliance Operator on the managed clusters.
#
# If set to "enforce" it'll install the operator.
#
# Note that OpenShift 4.18 is required.
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-odf-operator-install
  namespace: {{ .Values.policy_namespace }}
  annotations:
    policy.open-cluster-management.io/standards: NIST SP 800-53
    policy.open-cluster-management.io/categories: CA Security Assessment and Authorization
    policy.open-cluster-management.io/controls: CA-2 Security Assessments, CA-7 Continuous Monitoring
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: odf-operator-ns
        spec:
          remediationAction: enforce # will be overridden by remediationAction in parent policy
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: {{ .Values.odf.namespace }}
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1beta1
        kind: OperatorPolicy
        metadata:
          name: install-odf-operator
        spec:
          remediationAction: enforce
          severity: high
          complianceType: musthave
          operatorGroup:
            name: {{ .Values.odf.namespace }}
            namespace: {{ .Values.odf.namespace }}
            targetNamespaces:
              - {{ .Values.odf.namespace }}
          subscription:
            name: {{ .Values.odf.name }}
            namespace: {{ .Values.odf.namespace }}
            source: '{{ "{{" }}hub index .ManagedClusterLabels "autoshift.io/odf-source" | default "{{ .Values.odf.source }}" hub{{ "}}" }}'
            sourceNamespace: '{{ "{{" }}hub index .ManagedClusterLabels "autoshift.io/odf-source-namespace" | default "{{ .Values.odf.sourceNamespace }}" hub{{ "}}" }}'
          # Getting Label and then capitalizing first letter
          upgradeApproval: '{{ "{{hub" }} $upgrade_approval := index .ManagedClusterLabels "autoshift.io/odf-install-plan-approval" | default "{{ .Values.odf.installPlanApproval }}" {{ "-hub}}" }} {{ "{{hub" }} print (substr 0 1 $upgrade_approval | upper) (substr 1 (len $upgrade_approval) $upgrade_approval) {{ "-hub}}" }}'
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: odf-status
        spec:
          remediationAction: inform
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: ClusterServiceVersion
                metadata:
                  namespace: {{ .Values.odf.namespace }}
                spec:
                  displayName: OpenShift Data Foundation
                status:
                  phase: Succeeded # check the csv status to determine if operator is running or not
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: placement-policy-odf-operator-install
  namespace: {{ .Values.policy_namespace }}
spec:
  clusterSets:
  {{- range $clusterSet, $value := $.Values.managedClusterSets }}
    - {{ $clusterSet }}
  {{- end }}
  {{- range $clusterSet, $value := $.Values.hubClusterSets }}
    - {{ $clusterSet }}
  {{- end }}
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: 'autoshift.io/odf'
              operator: In
              values:
              - 'true'
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: placement-policy-odf-operator-install
  namespace: {{ .Values.policy_namespace }}
placementRef:
  name: placement-policy-odf-operator-install
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: policy-odf-operator-install
    apiGroup: policy.open-cluster-management.io
    kind: Policy
