# This policy verifies the installation of the official & supported version of
# the Compliance Operator on the managed clusters.
#
# If set to "enforce" it'll install the operator.
#
# Note that OpenShift 4.6 is required.
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-logging-install
  namespace: open-cluster-policies
  annotations:
    policy.open-cluster-management.io/standards: NIST SP 800-53
    policy.open-cluster-management.io/categories: CA Security Assessment and Authorization
    policy.open-cluster-management.io/controls: CA-2 Security Assessments, CA-7 Continuous Monitoring
spec:
  dependencies:
    - name: policy-logging-operator-install
      namespace: open-cluster-policies
      apiVersion: policy.open-cluster-management.io/v1
      compliance: Compliant
      kind: Policy
    - name: policy-loki-stack-install
      namespace: open-cluster-policies
      apiVersion: policy.open-cluster-management.io/v1
      compliance: Compliant
      kind: Policy    
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: logging-install
        spec:
          remediationAction: inform # will be overridden by remediationAction in parent policy
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                kind: ServiceAccount
                apiVersion: v1
                metadata:
                  name: collector
                  namespace: {{ .Values.logging.namespace }}
            - complianceType: musthave
              objectDefinition:
                kind: ClusterRoleBinding
                apiVersion: rbac.authorization.k8s.io/v1
                metadata:
                  name: collect-application-logs
                subjects:
                  - kind: ServiceAccount
                    name: collector
                    namespace: {{ .Values.logging.namespace }}
                roleRef:
                  apiGroup: rbac.authorization.k8s.io
                  kind: ClusterRole
                  name: collect-application-logs
            - complianceType: musthave
              objectDefinition:
                kind: ClusterRoleBinding
                apiVersion: rbac.authorization.k8s.io/v1
                metadata:
                  name: collect-audit-logs
                subjects:
                  - kind: ServiceAccount
                    name: collector
                    namespace: {{ .Values.logging.namespace }}
                roleRef:
                  apiGroup: rbac.authorization.k8s.io
                  kind: ClusterRole
                  name: collect-audit-logs
            - complianceType: musthave
              objectDefinition:
                kind: ClusterRoleBinding
                apiVersion: rbac.authorization.k8s.io/v1
                metadata:
                  name: collect-infrastructure-logs
                subjects:
                  - kind: ServiceAccount
                    name: collector
                    namespace: {{ .Values.logging.namespace }}
                roleRef:
                  apiGroup: rbac.authorization.k8s.io
                  kind: ClusterRole
                  name: collect-infrastructure-logs
            - complianceType: musthave
              objectDefinition:
                kind: ClusterRoleBinding
                apiVersion: rbac.authorization.k8s.io/v1
                metadata:
                  name: logging-collector-logs-writer
                subjects:
                  - kind: ServiceAccount
                    name: collector
                    namespace: {{ .Values.logging.namespace }}
                roleRef:
                  apiGroup: rbac.authorization.k8s.io
                  kind: ClusterRole
                  name: logging-collector-logs-writer
            - complianceType: musthave
              objectDefinition:
                apiVersion: observability.openshift.io/v1
                kind: ClusterLogForwarder
                metadata:
                  name: logging
                  namespace: {{ .Values.logging.namespace }}
                spec:
                  managementState: Managed
                  outputs:
                    - lokiStack:
                        authentication:
                          token:
                            from: serviceAccount
                        target:
                          name: logging-lokistack
                          namespace: {{ .Values.loki.namespace }}
                      name: logging-lokistack
                      tls:
                        ca:
                          configMapName: openshift-service-ca.crt
                          key: service-ca.crt
                      type: lokiStack
                  pipelines:
                    - inputRefs:
                        - infrastructure
                        - application
                      name: logs-to-loki
                      outputRefs:
                        - logging-lokistack
                  serviceAccount:
                    name: collector
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: placement-policy-logging-install
  namespace: open-cluster-policies
spec:
  clusterSets:
  {{- range .Values.logging.clusterSets }}
    - {{ . }}
  {{- end }}
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: placement-policy-logging-install
  namespace: open-cluster-policies
placementRef:
  name: placement-policy-logging-install
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: policy-logging-install
    apiGroup: policy.open-cluster-management.io
    kind: Policy
